packages:
  - apps/*
  - packages/*

catalog:
  "@hookform/resolvers": ^3.10.0
  "@next/eslint-plugin-next": ^15.1.0
  "@playwright/test": ^1.49.0
  "@radix-ui/react-slot": ^1.1.1
  "@tailwindcss/forms": ^0.5.9
  "@tailwindcss/typography": ^0.5.15
  "@tanstack/react-query": ^5.85.5
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  "@types/node": ^22.10.1
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@typescript-eslint/eslint-plugin": ^8.18.1
  "@typescript-eslint/parser": ^8.18.1
  "@vitejs/plugin-react": ^4.3.4
  "@vitest/ui": ^2.1.8
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^4.1.0
  eslint: ^9.16.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.0.0
  jsdom: ^25.0.1
  lucide-react: ^0.468.0
  next: ^15.1.0
  postcss: ^8.5.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-hook-form: ^7.54.0
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.17
  typescript: ^5.7.2
  vitest: ^2.1.8
  zod: ^3.24.1
  zustand: ^5.0.8
